name: Diagfusion
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.20
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - libffi=3.4.6
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - openssl=3.4.1
  - pip=24.3.1
  - setuptools=75.3.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.6.4
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - cycler==0.12.1
      - dgl==1.1.2
      - fasttext-wheel==0.9.2
      - filelock==3.16.1
      - fsspec==2025.3.0
      - idna==3.10
      - interchange==2021.0.4
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.2.2
      - monotonic==1.6
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.21.6
      - pandas==1.3.5
      - pansi==2024.11.0
      - pillow==10.4.0
      - py2neo==2021.2.4
      - pybind11==2.13.6
      - pyparsing==3.1.4
      - pytz==2022.2.1
      - pyyaml==6.0
      - requests==2.32.3
      - scikit-learn==1.1.2
      - scipy==1.10.1
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchdata==0.8.0
      - torchvision==0.15.2
      - tqdm==4.64.0
      - urllib3==2.2.3
      - utils==1.0.1