dataset: 'gaia'
base_path: '.'
demo_path: 'data/gaia/demo'
label: 'demo_1100'

parse:  # 数据预处理部分，是历史和在线故障都需要进行的预处理部分
  nodes: 'adservice  adservice-0 adservice-1 adservice-2 adservice2-0 cartservice cartservice-0 cartservice-2 cartservice2-0 checkoutservice checkoutservice checkoutservice-0 checkoutservice-2 checkoutservice2-0 currencyservice currencyservice-0 currencyservice-1 currencyservice-2 emailservice emailservice-0 emailservice-1 emailservice-2 frontend frontend-0 frontend-1 frontend-2 paymentservice paymentservice-0 paymentservice-1 paymentservice-2 productcatalogservice productcatalogservice-0 productcatalogservice-1 productcatalogservice-2 productcatalogservice2-0 recommendationservice recommendationservice-0 recommendationservice-1 recommendationservice-2 recommendationservice2-0 shippingservice shippingservice-0 shippingservice-1 shippingservice-2 shippingservice2-0'
  parse_dir: 'parse'
  metric_path: 'anomalies/AIOps指标-metric_events_aiops_sensitive.json'
  trace_path: 'anomalies/AIOps调用-trace_events_aiops.json' 
  log_path: 'anomalies/stratification_logs.npy' 
  save_path: 'parse/stratification_texts.pkl' #统一格式后的文本文件路径

fasttext: # 对于历史故障的特征学习
  supervised: True
  dataset: 'gaia'
  nodes: 'adservice  adservice-0 adservice-1 adservice-2 adservice2-0 cartservice cartservice-0 cartservice-2 cartservice2-0 checkoutservice checkoutservice checkoutservice-0 checkoutservice-2 checkoutservice2-0 currencyservice currencyservice-0 currencyservice-1 currencyservice-2 emailservice emailservice-0 emailservice-1 emailservice-2 frontend frontend-0 frontend-1 frontend-2 paymentservice paymentservice-0 paymentservice-1 paymentservice-2 productcatalogservice productcatalogservice-0 productcatalogservice-1 productcatalogservice-2 productcatalogservice2-0 recommendationservice recommendationservice-0 recommendationservice-1 recommendationservice-2 recommendationservice2-0 shippingservice shippingservice-0 shippingservice-1 shippingservice-2 shippingservice2-0'
  text_path: 'parse/stratification_texts.pkl' # 输入统一后的文本文件路径
  fasttext_dir: 'fasttext'
  temp_dir: 'fasttext/temp'
  train_path: 'fasttext/temp/train.txt'
  test_path: 'fasttext/temp/test.txt'
  train_da_path: 'fasttext/temp/train_da.txt'
  save_path: 'fasttext/event_embedding.pkl' # FastText事件嵌入结果保存路径
  vector_dim: 100
  sample_count: 1000
  edit_count: 1
  da_method: 'w2v'
  minCount: 1
  epoch: 5

sentence_embedding: # 历史故障的序列编码
  K_S: 10 
  train_path: 'fasttext/temp/train.txt'
  test_path: 'fasttext/temp/test.txt'
  source_path: 'fasttext/event_embedding.pkl'
  save_path: 'sentence_embedding.pkl'  # 用于后续新故障来的时候进行在线的推理

he_dgl: # 异构图神经网络部分
  nodes: 'adservice  adservice-0 adservice-1 adservice-2 adservice2-0 cartservice cartservice-0 cartservice-2 cartservice2-0 checkoutservice checkoutservice checkoutservice-0 checkoutservice-2 checkoutservice2-0 currencyservice currencyservice-0 currencyservice-1 currencyservice-2 emailservice emailservice-0 emailservice-1 emailservice-2 frontend frontend-0 frontend-1 frontend-2 paymentservice paymentservice-0 paymentservice-1 paymentservice-2 productcatalogservice productcatalogservice-0 productcatalogservice-1 productcatalogservice-2 productcatalogservice2-0 recommendationservice recommendationservice-0 recommendationservice-1 recommendationservice-2 recommendationservice2-0 shippingservice shippingservice-0 shippingservice-1 shippingservice-2 shippingservice2-0'
  dataset: 'gaia'
  heterogeneous: False # 图的类型配置，True表示异构图，False表示同构图
  data_dir: ''
  save_dir: 'dgl/stratification_10' # 保存模型的路径
  Xs: 'sentence_embedding.pkl'  # 节点特征向量（来自多模态特征提取）
  run_table: 'merged_groundtruth.csv' # 'demo_train160.csv'
  aug: False
  aug_size: 0
  N_S: 16 
  N_A: 9
  TOPK_SA: 10
  # save_model: False # 新故障处理时启用（推理模式）
  save_model: True  # 历史故障处理时启用（训练模式）
  epoch: 6000 # 训练的时候的epoch数
  batch_size: 1000 
  win_size: 50        # 增大窗口大小，确保更长时间的稳定性
  win_threshold: 0.00001  # 降低阈值，要求更严格的收敛标准
  lr: 0.001
  weight_decay: 0.0001
  seed: 2
  text_path: 'parse/stratification_texts.pkl'
  
  # *** 新增配置：解决 IndexError: Target 14 is out of bounds 问题 ***
  num_classes: 50           # 设置足够大的类别数，确保覆盖所有可能的标签
  auto_detect_classes: True # 启用自动检测类别数
  
  # 标签相关配置（可选）
  service_classes: 44       # 根据 nodes 数量计算：44个服务/实例
  anomaly_classes: 10       # 根据 fasttext 输出：10种异常类型
  label_combination: 'multiply'  # 标签组合方式：'multiply' 或 'add'
  
  # 调试和验证配置
  debug_labels: True        # 启用标签调试信息
  validate_labels: True     # 训练前验证标签范围
